// test/modelVerification.js
// Verificación simple de archivos de modelo TensorFlow.js

const fs = require('fs');
const path = require('path');

function verifyModelFiles() {
  console.log('🧪 Verificando archivos de modelo TensorFlow.js...\n');
  
  // Directorio del modelo
  const modelDir = path.join(__dirname, '../assets/Modelo/tfjs_model');
  
  // Archivos esperados
  const expectedFiles = [
    'model.json',
    'group1-shard1of3.bin',
    'group1-shard2of3.bin', 
    'group1-shard3of3.bin'
  ];
  
  let allFilesValid = true;
  
  // Verificar que el directorio existe
  if (!fs.existsSync(modelDir)) {
    console.error(`❌ Directorio de modelo no existe: ${modelDir}`);
    return false;
  }
  
  console.log(`📁 Directorio de modelo: ${modelDir}`);
  
  // Verificar cada archivo
  expectedFiles.forEach(fileName => {
    const filePath = path.join(modelDir, fileName);
    
    if (fs.existsSync(filePath)) {
      const stats = fs.statSync(filePath);
      const sizeKB = Math.round(stats.size / 1024);
      console.log(`✅ ${fileName} - ${sizeKB} KB`);
    } else {
      console.error(`❌ ${fileName} - NO ENCONTRADO`);
      allFilesValid = false;
    }
  });
  
  console.log('\n📊 Verificando contenido de model.json...');
  
  try {
    const modelJsonPath = path.join(modelDir, 'model.json');
    const modelJson = JSON.parse(fs.readFileSync(modelJsonPath, 'utf8'));
    
    console.log('📋 Información del modelo:');
    console.log(`   - Format: ${modelJson.format || 'no especificado'}`);
    console.log(`   - Generated by: ${modelJson.generatedBy || 'no especificado'}`);
    console.log(`   - Model topology definido: ${!!modelJson.modelTopology}`);
    console.log(`   - Weights manifest: ${modelJson.weightsManifest ? modelJson.weightsManifest.length + ' entradas' : 'no definido'}`);
    
    if (modelJson.weightsManifest) {
      console.log('📦 Archivos de pesos referenciados:');
      modelJson.weightsManifest.forEach((manifest, index) => {
        if (manifest.paths) {
          manifest.paths.forEach(pathName => {
            console.log(`   - ${pathName}`);
          });
        }
      });
    }
    
  } catch (error) {
    console.error('❌ Error leyendo model.json:', error.message);
    allFilesValid = false;
  }
  
  console.log('\n🎯 Resultado de verificación:');
  if (allFilesValid) {
    console.log('✅ Todos los archivos de modelo están presentes y válidos');
    console.log('🚀 El modelo debería poder cargarse en TensorFlow.js');
  } else {
    console.log('❌ Faltan archivos o hay errores en el modelo');
    console.log('🔧 Es necesario regenerar los archivos del modelo');
  }
  
  return allFilesValid;
}

// Función adicional para verificar el modelo YOLOv8 original
function verifyOriginalModel() {
  console.log('\n🔍 Verificando modelo YOLOv8 original...');
  
  const originalModelPath = path.join(__dirname, '../assets/Modelo/yolov8n.pt');
  const savedModelPath = path.join(__dirname, '../assets/Modelo/runs/detect/train/weights/best_saved_model');
  
  if (fs.existsSync(originalModelPath)) {
    const stats = fs.statSync(originalModelPath);
    const sizeMB = Math.round(stats.size / (1024 * 1024));
    console.log(`✅ Modelo PyTorch original: yolov8n.pt - ${sizeMB} MB`);
  } else {
    console.log('❌ Modelo PyTorch original no encontrado');
  }
  
  if (fs.existsSync(savedModelPath)) {
    console.log('✅ SavedModel disponible para conversión');
  } else {
    console.log('❌ SavedModel no disponible');
  }
}

// Ejecutar verificaciones
if (require.main === module) {
  console.log('🔬 Verificación de Modelo TensorFlow.js');
  console.log('=====================================');
  
  const isValid = verifyModelFiles();
  verifyOriginalModel();
  
  console.log('\n📄 Resumen final:');
  console.log(`Estado del modelo: ${isValid ? '✅ VÁLIDO' : '❌ INVÁLIDO'}`);
  
  process.exit(isValid ? 0 : 1);
}

module.exports = { verifyModelFiles, verifyOriginalModel };